#! /bin/sh

#
#   Copyright 2015-2018 Kai Huebl (kai@huebl-sgh.de)
#
#   Lizenziert gemäß Apache Licence Version 2.0 (die „Lizenz“); Nutzung dieser
#   Datei nur in Übereinstimmung mit der Lizenz erlaubt.
#   Eine Kopie der Lizenz erhalten Sie auf http://www.apache.org/licenses/LICENSE-2.0.
#
#   Sofern nicht gemäß geltendem Recht vorgeschrieben oder schriftlich vereinbart,
#   erfolgt die Bereitstellung der im Rahmen der Lizenz verbreiteten Software OHNE
#   GEWÄHR ODER VORBEHALTE – ganz gleich, ob ausdrücklich oder stillschweigend.
#
#   Informationen über die jeweiligen Bedingungen für Genehmigungen und Einschränkungen
#   im Rahmen der Lizenz finden Sie in der Lizenz.
#
#   Autor: Kai Huebl (kai@huebl-sgh.de), Aleksey Timin (atimin@gmail.com)
#

echo "POSTINST RUN"

if [ -x /sbin/start ] && [ -e "/etc/init/ProjectName.conf" ]; then
    # use upstart
    echo "INFO: starting daemon by upstart"
    /sbin/start ProjectName
elif [ -x /usr/bin/systemctl ] && [ -e "/usr/lib/systemd/system/ProjectName.service" ]; then
    # use systemd
    echo "INFO: starting daemon by systemd"
    /usr/bin/systemctl enable ProjectName.service
    /usr/bin/systemctl start ProjectName.service
else
    # use SYSV init script
    echo "INFO: starting SYSV init script"
    if [ -x "/etc/init.d/ProjectName" ]; then
        update-rc.d ProjectName defaults >/dev/null
        invoke-rc.d ProjectName start || exit $?
    fi
fi

/sbin/ldconfig

echo "POSTINST RETURN"
exit 0
