name: Ubuntu 22.04 LTS Build & Test
run-name: ${{ github.actor }} is testing on Ubuntu 22.04 LTS 🚀
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get install libboost-all-dev cmake libssl-dev  build-essential

      - name: Build Project
        run: |
          sh build.sh -t local

      - name: Build Test
        run: |
          sh build.sh -t tst -s ~/.ASNeG/

      - run: echo "This job's status is ${{ job.status }}."
