#! /bin/sh

#
#   Copyright 2015 Kai Huebl (kai@huebl-sgh.de)
#
#   Lizenziert gemäß Apache Licence Version 2.0 (die „Lizenz“); Nutzung dieser
#   Datei nur in Übereinstimmung mit der Lizenz erlaubt.
#   Eine Kopie der Lizenz erhalten Sie auf http://www.apache.org/licenses/LICENSE-2.0.
#
#   Sofern nicht gemäß geltendem Recht vorgeschrieben oder schriftlich vereinbart,
#   erfolgt die Bereitstellung der im Rahmen der Lizenz verbreiteten Software OHNE
#   GEWÄHR ODER VORBEHALTE – ganz gleich, ob ausdrücklich oder stillschweigend.
#
#   Informationen über die jeweiligen Bedingungen für Genehmigungen und Einschränkungen
#   im Rahmen der Lizenz finden Sie in der Lizenz.
#
#   Autor: Kai Huebl (kai@huebl-sgh.de)
#

echo "PRERM RUN"

if [ -x /sbin/stop ] && [ -e "/etc/init/ASNeG-Demo.conf" ]; then
    # use Ubuntu upstart
    echo "INFO: stopping daemon by upstart"
    /sbin/stop ASNeG-Demo 
elif [ -x /usr/bin/systemctl ] && [ -e "/usr/lib/systemd/system/ASNeG-Demo.service" ]; then
    # use systemd
    echo "INFO: stopping  daemon by systemd"
    /usr/bin/systemctl stop ASNeG-Demo.service
    /usr/bin/systemctl enable ASNeG-Demo.service
else
    # use SYSV init script
    if [ -e "/etc/init.d/ASNeG-Demo" ]; then
        echo "INFO: stopping daemon by SYS init script"
        invoke-rc.d ASNeG-Demo stop || exit $?
        update-rc.d -f ASNeG-Demo remove >/dev/null
    fi
fi

echo "PRERM RETURN"
exit 0

